# This block handles HTTP traffic
server {
    if ($host = www.mora-scent.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = mora-scent.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name mora-scent.com www.mora-scent.com;

    # Redirect all other HTTP traffic for this domain to HTTPS
    return 301 https://$host$request_uri;
}

# This block handles HTTPS traffic
server {
    listen 443 ssl;
    server_name mora-scent.com www.mora-scent.com;

    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;
   
    access_log /var/log/nginx/mora-scent_access.log;
    error_log /var/log/nginx/mora-scent_error.log;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

    location / {
        root /home/youssef/mora-scent/frontend/dist;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:2533/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-NginX-Proxy true;
    }

    location /admin/ {
        proxy_pass http://127.0.0.1:2533/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-NginX-Proxy true;
    }

    location /static/ {
        alias /usr/src/app/mora-scent/staticfiles/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias /usr/src/data/media/;
        expires 7d; # Cache media files in browser for 7 days
        add_header Cache-Control "public";
    }
    ssl_certificate /etc/letsencrypt/live/mora-scent.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mora-scent.com/privkey.pem; # managed by Certbot



}
